In [1]:
print('Ritu')

Ritu


In [3]:
import numpy as np
import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer
from gensim.utils import simple_preprocess

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [4]:
df = pd.DataFrame({'text':['people watch campusx','campusx watch campusx','ritu write comment for campusx','campusx write comment'],'output':[1,1,0,0]})
df

text  output
0            people watch campusx       1
1           campusx watch campusx       1
2  ritu write comment for campusx       0
3           campusx write comment       0

In [6]:
cv = CountVectorizer()

In [7]:
bow = cv.fit_transform(df.text) 

In [9]:
cv.vocabulary_

{'people': 3,
 'watch': 5,
 'campusx': 0,
 'ritu': 4,
 'write': 6,
 'comment': 1,
 'for': 2}

In [11]:
print(df.text[0])
print(bow[0].toarray())

people watch campusx
[[1 0 0 1 0 1 0]]


In [12]:
cv1  =CountVectorizer(binary = True)

In [14]:
bow1 = cv1.fit_transform(df['text'])

In [16]:
cv1.vocabulary_

{'people': 3,
 'watch': 5,
 'campusx': 0,
 'ritu': 4,
 'write': 6,
 'comment': 1,
 'for': 2}

In [17]:
df

text  output
0            people watch campusx       1
1           campusx watch campusx       1
2  ritu write comment for campusx       0
3           campusx write comment       0

In [18]:
bow1[1].toarray()

array([[1, 0, 0, 0, 0, 1, 0]], dtype=int64)

In [20]:
cv3 = CountVectorizer(ngram_range = (1,2))
bow3 = cv3.fit_transform(df.text)
print(cv3.vocabulary_)
print(df.text[0])
print(bow3[0].toarray())

{'people': 7, 'watch': 11, 'campusx': 0, 'people watch': 8, 'watch campusx': 12, 'campusx watch': 1, 'ritu': 9, 'write': 13, 'comment': 3, 'for': 5, 'ritu write': 10, 'write comment': 14, 'comment for': 4, 'for campusx': 6, 'campusx write': 2}
people watch campusx
[[1 0 0 0 0 0 0 1 1 0 0 1 1 0 0]]


In [22]:
tfi = TfidfVectorizer()
tf = tfi.fit_transform(df.text).toarray()

In [23]:
tfi.vocabulary_

{'people': 3,
 'watch': 5,
 'campusx': 0,
 'ritu': 4,
 'write': 6,
 'comment': 1,
 'for': 2}

In [24]:
tf[0]

array([0.37919167, 0.        , 0.        , 0.72664149, 0.        ,
       0.5728925 , 0.        ])

In [26]:
len(tf[0])

7

In [72]:
import gensim.downloader as api 
from gensim.models import Word2Vec

In [32]:
# wtv = api.load('word2vec-google-news-300')
# wv = api.load('word2vec-google-news-300') 

In [33]:
import os 
import pathlib

In [35]:
os.listdir()

['.ipynb_checkpoints',
 'dome.txt',
 'Text-Representation1.ipynb',
 'Text_preprocessing1.ipynb']

In [47]:
curent_path = pathlib.Path(r'E:\kaushal\data science\nlp\code\campusx\TRANING\AGameOfThrones')
curent_path

WindowsPath('E:/kaushal/data science/nlp/code/campusx/TRANING/AGameOfThrones')

In [58]:
lemma = WordNetLemmatizer()

In [68]:
corpus = []
for file in curent_path.glob('*'):
    for line in file.read_text().split('\n'):
        # print(simple_preprocess(line))
        corpus.append([lemma.lemmatize(word) for word in simple_preprocess(line) if word not in stopwords.words('english')])


In [69]:
corpus

[['game', 'throne'],
 ['book', 'one', 'song', 'ice', 'fire'],
 ['george', 'martin'],
 ['prologue'],
 ['start',
  'back',
  'gared',
  'urged',
  'wood',
  'began',
  'grow',
  'dark',
  'around',
  'wildlings'],
 ['dead'],
 ['dead', 'frighten', 'ser', 'waymar', 'royce', 'asked', 'hint', 'smile'],
 ['gared',
  'rise',
  'bait',
  'old',
  'man',
  'past',
  'fifty',
  'seen',
  'lordlings',
  'come',
  'go'],
 ['dead', 'dead', 'said', 'business', 'dead'],
 ['dead', 'royce', 'asked', 'softly', 'proof'],
 ['saw', 'gared', 'said', 'say', 'dead', 'proof', 'enough'],
 ['known',
  'would',
  'drag',
  'quarrel',
  'sooner',
  'later',
  'wished',
  'later',
  'rather'],
 ['sooner', 'mother', 'told', 'dead', 'men', 'sing', 'song', 'put'],
 ['wet',
  'nurse',
  'said',
  'thing',
  'royce',
  'replied',
  'never',
  'believe',
  'anything',
  'hear',
  'woman'],
 ['tit',
  'thing',
  'learned',
  'even',
  'dead',
  'voice',
  'echoed',
  'loud',
  'twilit',
  'forest'],
 ['page'],
 [],
 ['long

In [73]:
wtv = Word2Vec(window = 5,min_count = 2)

In [74]:
wtv.build_vocab(corpus)

In [76]:
dir(wtv)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_adapt_by_suffix',
 '_check_corpus_sanity',
 '_check_training_sanity',
 '_clear_post_train',
 '_do_train_epoch',
 '_do_train_job',
 '_get_next_alpha',
 '_get_thread_working_mem',
 '_job_producer',
 '_load_specials',
 '_log_epoch_end',
 '_log_epoch_progress',
 '_log_progress',
 '_log_train_end',
 '_raw_word_count',
 '_save_specials',
 '_scan_vocab',
 '_smart_save',
 '_train_epoch',
 '_train_epoch_corpusfile',
 '_worker_loop',
 '_worker_loop_corpusfile',
 'add_lifecycle_event',
 'add_null_word',
 'alpha',
 'batch_words',
 'build_vocab',
 'build_vocab_from_freq',
 'cbow_mean',
 'comment',
 'compute_loss',
 

In [79]:
wtv.train(corpus,total_examples = wtv.corpus_count,epochs = wtv.epochs)

(4384266, 4579390)

In [80]:
wtv.epochs

5

In [82]:
wtv.wv.most_similar('daenerys')

[('viserys', 0.9126228094100952),
 ('elia', 0.8765827417373657),
 ('myrcella', 0.8603630661964417),
 ('targaryen', 0.8584360480308533),
 ('treason', 0.8568501472473145),
 ('princess', 0.8565565347671509),
 ('hizdahr', 0.8527028560638428),
 ('whore', 0.8498767614364624),
 ('sake', 0.8458649516105652),
 ('font', 0.8429198861122131)]

In [85]:
wtv.wv.doesnt_match(['jon','rikon','robb','arya','sansa','bran'])

'jon'

In [86]:
wtv.wv['king']

array([ 1.4806442 , -0.97301877,  2.1338167 ,  0.49205622, -0.8724741 ,
       -0.6466923 , -1.0513003 ,  0.08126272, -0.586643  , -0.70823705,
       -0.3153404 , -1.162721  ,  0.7379377 ,  0.48125774,  0.37101573,
        1.6127894 ,  0.23226833,  0.5517271 , -0.99936324, -2.8012023 ,
       -0.1267026 ,  1.7569046 , -0.3914482 , -1.7031149 , -0.36559266,
        1.260172  , -0.6349771 ,  0.3108242 , -0.7377513 ,  1.8649305 ,
       -0.20751353,  0.51949316, -0.4351358 , -1.1289047 , -0.87487423,
        0.02245147, -0.49320945, -0.342106  , -0.8023019 ,  0.04329238,
       -0.59109974, -1.2777916 ,  0.00315892, -0.26948297,  0.6679783 ,
       -0.66704273, -0.91682357, -0.8204056 ,  1.5695802 ,  0.2886014 ,
       -0.5774803 , -0.12445973,  1.6095936 , -0.9589427 , -0.11072636,
        2.0732436 , -1.3571403 ,  0.8801556 , -0.09914835,  0.12323038,
        0.81399715,  0.6419403 , -1.6191887 ,  2.065731  , -0.91271824,
        1.6971012 , -1.3281882 ,  1.4966412 ,  0.5250644 ,  0.53

In [88]:
wtv.wv.index_to_key

['said',
 'lord',
 'would',
 'one',
 'ser',
 'could',
 'man',
 'king',
 'hand',
 'men',
 'back',
 'well',
 'like',
 'jon',
 'eye',
 'know',
 'father',
 'old',
 'time',
 'even',
 'tyrion',
 'never',
 'see',
 'brother',
 'made',
 'lady',
 'black',
 'told',
 'thought',
 'come',
 'face',
 'boy',
 'son',
 'head',
 'long',
 'wall',
 'might',
 'u',
 'day',
 'way',
 'say',
 'still',
 'red',
 'night',
 'page',
 'sword',
 'good',
 'queen',
 'must',
 'two',
 'knight',
 'little',
 'took',
 'make',
 'came',
 'woman',
 'though',
 'girl',
 'take',
 'want',
 'go',
 'three',
 'away',
 'dead',
 'blood',
 'half',
 'look',
 'horse',
 'word',
 'arya',
 'need',
 'god',
 'saw',
 'white',
 'foot',
 'jaime',
 'first',
 'tell',
 'child',
 'much',
 'enough',
 'bran',
 'great',
 'arm',
 'looked',
 'left',
 'knew',
 'asked',
 'gave',
 'maester',
 'called',
 'every',
 'let',
 'heard',
 'sansa',
 'yet',
 'went',
 'turned',
 'dany',
 'castle',
 'behind',
 'keep',
 'snow',
 'around',
 'year',
 'another',
 'grace',
 't

In [89]:
wtv.wv.similarity('tywin','sansa')

0.3363125

In [90]:
wtv.wv.most_similar('king')

[('baratheon', 0.7480459809303284),
 ('bloodlust', 0.6652341485023499),
 ('onset', 0.6379607915878296),
 ('rebellion', 0.6290974617004395),
 ('throne', 0.6249133348464966),
 ('potential', 0.6224945783615112),
 ('loses', 0.6156949996948242),
 ('dragonstone', 0.6036375164985657),
 ('prince', 0.6028984785079956),
 ('royal', 0.6010097861289978)]

In [91]:
wtv.wv.similarity('king','baratheon')

0.74804616